on:
  issues:
    types: [ opened, labeled ]
name: Issues
jobs:
  issueHandler:
    runs-on: windows-latest
    name: Issue Verification
    steps:
      - uses: actions/checkout@main
      - name: Verify Issue
        uses: specter119/ShovelAction@main
        if: github.event.action == 'opened' || (github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'verify'))
        env:
          GITH_EMAIL: specter119@gmail.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
